export const cityName = {
  대구: "daegu",
  충남: "chungnam",
  인천: "incheon",
  경북: "gyeongbuk",
  대전: "daejeon",
  세종: "sejong",
  광주: "gwangju",
  전북: "jeonbuk",
  강원: "gangwon",
  울산: "ulsan",
  전남: "jeonnam",
  서울: "seoul",
  부산: "busan",
  제주: "jeju",
  충북: "chungbuk",
  경남: "gyeongnam",
  경기: "gyeonggi",
};
